version: "3.9" # DOCKER COMPOSE VERSION.

services:
  # BACKEND
  plutus:
    build:
      context: .
      dockerfile: plutus/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
    depends_on:
      - mongo
    networks:
      - plutus-network
  
  # DATABASE
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--noauth"]  # Disables authentication
    networks:
      - plutus-network

volumes:
  mongo-data:

networks:
  plutus-network:
    driver: bridge